services:
  db:
    # MEDIUM DB RESOURCE LIMITS
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

    # Ports are NOT exposed externally (no 5432:5432)

  api:
    # NO HOT RELOAD

    # STANDARD LOGGING: Switch to production mode.
    environment:
      FLASK_ENV: production

    # Ports are NOT exposed externally (no 8000:8000), only reachable via Nginx.

  nginx:
    # HTTPS ACCESS
    image: nginx:stable-alpine
    ports:
      - "443:443"
    depends_on:
      - api
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/branchloans.crt:/etc/nginx/certs/branchloans.crt:ro
      - ./nginx/branchloans.key:/etc/nginx/certs/branchloans.key:ro
